name: Playwright BDD Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install

    - name: Install Allure CLI
      run: npm install -g allure-commandline

    - name: Run Playwright Tests
      run: npx playwright test

    - name: Generate Allure Report
      run: |
        allure generate ./allure-results -o ./allure-report --clean

    - name: Upload Allure Report
      if: always()  
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-report
